* Proyecto: Sucedió en colores

Se propone una secuencia de trabajo sobre la lectura del libro de cuentos "Sucedió en colores"[^fn:1]. La particularidad de este proyecto es que se puede abordar un cuento cada dos sesiones de trabajo, de forma que a pesar de las ausencias salteadas de algunos estudiantes, estos, cada vez que asisten al grupo de trabajo, pueden incluirse sin perder el hilo del proyecto. Son dos encuentros autoconlusivos por cada cuento.

Para el desarrollo de esta propuesta de enseñanza se espera que cada niño cuente con la posibilidad de contar con un ejemplar del libro o en su defecto, un ejemplar del cuento de forma impresa o digital. Sustenta la propuesta brindar la oportunidad de transitar por diversas situaciones de
lectura y escritura:

- lectura por parte del maestro;
- sucesivos intercambios entre lectores;
- lectura de la biografía del autor para saber más sobre su vida y obra con escrituras de toma de notas a través del dictado al maestro;
- lectura de la biografía del ilustrador;
- lectura en pequeños grupos;
- lectura por sí mismos;
- escritura por sí mismos (individualmente, en parejas y en grupos pequeños) a partir de las lecturas realizadas.

** Rojo:
*** Lectura por parte del maestro

Los maestros presentan el cuento, leen mostrando el título y el nombre del autor. Escriben los datos del autor y del nombre del libro en un afiche para que queden disponibles como referencias seguras (que pueden utilizarse para otras escrituras). Esto puede ser el punta pie para comenzar a hacer un rincón en las paredes del aula de escrituras sobre el mismo. Este es un buen momento para preguntar a los chicos y chicas si se imagina por qué se llama así el cuento, a fin de anticipar los distintos tipos de imágenes que convoca el cuento para decir rojo... sin decirlo nunca

- Lectura de cuento completo sin saltear párrafos ni sustituir palabras.
- Intercambio entre lectores: Este es un itinerario para el intercambio que está a modo de ejemplo, cada grupo, cada docente puede ir por donde lo lleve el momento. Lo que es importante es que este intercambio sirva para:
  - hablar sobre lo leído,
  - retomar partes del libro a fin de aclarar dudas con el texto en mano.
Se puede empezar el intercambio convocando a los chicos y chicas a entrar al libro desde las suposiciones que tenemos sobre los prototipos de los personajes:
  - ¿Se imaginaban al Diablo Así.... Enamorado?
  - ¿Cómo era este diablo enamorado?
  - ¿De quién se había enamorado el Diablo?
  - ¿Y su madrina?
  - ¿Por qué al final del cuento la madrina dice ?
#+begin_quote
La madrina del diablo abandonó su decaimiento, y se pasó al absoluto asombro. ¿De dónde había salido aquella joven bruja? Ella nunca la había visto. Ni siquiera había escuchado hablar de una hechicera pelirroja.
#+end_quote
- ¿A quién se refería con eso de hechicera pelirroja?
- ¿El diablo se juntó con Rubilda?
- ¿Pudo encantarla con el hechizo?
- ¿Quién encantó a quién?
- ¿Cómo era el encantamiento?

#+begin_quote
Es interesante releer en voz alta y para todos con distintos propósitos: para hacer notar la belleza de una expresión o advertir la intervención de un personaje o la parte más atrapante de la historia; para precisar una interpretación que resulte dudosa o para confirmar o rectificar apreciaciones diferentes cuando se genera una discrepancia entre los niños.
-- Propuesta la niña que iluminó la noche
#+end_quote

*** Propuestas de escritura
Estas son posibles propuestas para iniciar algunas escrituras intermedias.

- El cuento nombra muchas cosas que nos dan la idea o la sensación de que son rojas. Hagamos un listado de estos elementos que nos llevan a la idea del Rojo o de las cosas Rojas.
- Finalizada la escritura se puede hacer un afiche por dictado al maestro para ir organizando el ambiente alfabetizador.

*** Lectura por parte del maestro con un ejemplar para cada estudiante

En esta instancia recapitularemos lo que leímos la sesión anterior y les contamos que vamos a leer un fragmento del cuento, en este caso la parte en que el diablo le cuenta a la madrina de su amor y ella le enseña el hechizo. Podemos pedir a los estudiantes que localicen la parte en el cuento a partir de la ubicación de la primer ilustración (en la edición de Alfaguara Infantil) o guiarlos hasta las cercanías del inicio de esa parte del cuento para que ubiquen el párrafo.
#+begin_quote
A causa de tanto amor, el diablo dejó de lado sus obligaciones.
#+end_quote
Leemos el fragmento y los estudiantes siguen con el dedo la lectura en sus ejemplares.

*** Propuesta de escritura un poco más extensa.

A partir de la lectura se puede organizar un dialogo con los chicos y chicas para poder escribir con algunas o todas propuestas.

- ¿Qué preguntas podría haber hecho el Diablo para conquistar a Rubilda?
- ¿Qué otro hechizo se te ocurre que podía haber usado para conquistarla?
- ¿Qué pensás que le puede haber dicho la madrina del Diablo cuando falló la segunda vez?

#+begin_quote
Esa madrugada, en el "mercado de las rosas", nadie sospechó que el Diablo andaba cerca porque el grandioso dueño del fuego había tomado la apariencia de hombre elegante. Sin embargo, todos se apartaban un poco de su camino. Y al pasar de largo, sentían un escalofrío."
#+end_quote

** Blanco: 
*** Lectura pro parte del maestro

Los maestros presentan el cuento, leen mostrando el título y el nombre del autor. Escriben los datos del autor y del nombre del libro en un afiche para que queden disponibles como referencias seguras (que pueden utilizarse para otras escrituras). Esto puede ser el punta pie para comenzar a hacer un rincón en las paredes del aula de escrituras sobre el mismo. Este es un buen momento para preguntar a los chicos y chicas si se imagina por qué se llama así el cuento, a fin de anticipar los distintos tipos de imágenes que convoca el cuento para decir rojo... sin decirlo nunca

1. Imaginá que nuevos personajes se prdrían sumar a la historia del cuento "Blanco" (tené en cuenta el título).
2. Buscá en el cuento una frase que utilice la autora para que podamos imaginarnos un mundo blanco. Escribila en la carpeta (no te olvides de  ponerlo entre comillas).
3. Leé el sigueinte fragmento del cuento y a partir de ahí escribí otro posible final para esta historia. Te damos algunas ideas: puede aparecer un personaje nuevo, pueden llegar a un acuerdo el lobo y el oso, la luna puede empezar a hablar.
  > "El oso clavó sus garras en la luna, justo cuando el lobo clavaba sus colmillos. Los dos animales tironearon con fuerza porque ninguno quería soltar lo que había casado. Entonces..."

*** Amarillo: Lectura del maestro. Completar la historia

1. En un momento de la historia, el emperador tomó su pluma, un trozo de pergamino y escribió una larga lista de posibles enemigos ¿Quiénes podrían aparecer en esa lista?
2. Pero realmente ¿Quién era el verdadero enemigo del emperador que sólo aparecía cuando dormía la siesta?
3. ¿Qué otros remedios se les ocurre para espantar los sueños desagradables?
4. Leé el siguiente fragmento de "Amarillo" e inventá un nuevo conflicto y resolución para este cuento:
> "Todo comenzó durante una calurosa siesta de verano, cuando el durmiente emperador..."

*** Verde: Lectura individual. Completar partes

Con el "Cuento en mano", completá las oraciones que faltan para completar la red de acciones que sucedieron en el cuento

El campesino escupió un carozo de aceituna.
El carozo dio justo en la cabeza de una ran y la rana se murió, por eso...

---

El lugar se llenó de lagrimas y suspiros, entonces...

---

Los loros pasaron junto a la ventana de Esmeralda y la despertaron.

---
---
---

... el guardia miró la pantalla conectada al radar que detectaba plagas.

---
---

¡Y adiós, mala tormenta!


*** Verde: Imaginación

1. Teniendo en cuenta el título del cuento. ¿Qué otras desgracias se te ocurren que podrían haber llegado al campo de estos personajes?
2. Pensá y escribí unos carteles que la señora del campesino podría haber escrito para pegar en el pueblo y así advertir a los vecinos de que una desgracia se avecinaba.
3. Imaginá que el Guardián del Instituto Agronómico de Parques, Prados y Praderas, hubiera tenido que avisar a las patrullas de fumigación por teléfono. Escribí que te imaginás que hubiera dicho.
¿Y si hubiera sido por mail? Escribilo.

*** Negro: Lectura del maestro

1. Bruno pensaba que era el último día de su vida ¿Qué cosas hizo por ser su último día?
2. ¿Quién era en verdad la señora que parecía ser la muerte?
3. Al final de la historia Bruno se va a buscar a Melania ¿Habrán ido a pasear? ¿Dónde? ¿Qué le habrá contado Bruno? ¿Le habrá pedido ser la novia? Escribí un diálogo posible del paseo entre Melania y Bruno, no te olvides que el cuento se llama Negro.
* Footnotes

[^fn:1] [[http://maestromasmaestro.com.ar/wp-content/uploads/2013/11/2%C2%B0-Autor-GM-Lectura-de-novelas1.pdf][secuencia en base a "Leer novelas de Graciela Montes y “Tengo un montruo en el bolsillo" del programa Maestros Más Maestros]] y en [[https://docs.google.com/file/d/0B4I3zmAwvYg_S1NUdExVRXdiWHc/edit][La niña que iluminó la noche del Programa de Aceleración]]
